apiVersion: v1
kind: Service
metadata:
  name: {{ include "bizflow-nh.fullname" . }}-api
  labels:
    {{- include "bizflow-nh.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bizflow-nh.fullname" . }}-dashboard
  labels:
    {{- include "bizflow-nh.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: dashboard
  ports:
    - port: 4322
      targetPort: 4322
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bizflow-nh.fullname" . }}-pdf-sidecar
  labels:
    {{- include "bizflow-nh.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: pdf-sidecar
  ports:
    - port: 3100
      targetPort: 3100
