apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bip.fullname" . }}-admin
  labels:
    {{- include "bip.labels" . | nindent 4 }}
type: Opaque
stringData:
  NR_ADMIN_USER: {{ .Values.admin.username | quote }}
  NR_ADMIN_PASS: {{ .Values.admin.password | quote }}
