{{- range .Values.imagePullSecrets }}
{{- if not (lookup "v1" "Secret" $.Release.Namespace .name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "bip.labels" $ | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
type: kubernetes.io/dockerconfigjson
data: {}
{{- end }}
{{- end }}
